// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/user_category.dart';
import 'data/models/user_financial_item.dart';
import 'data/models/user_item.dart';
import 'data/models/user_work_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 4474380120461272255),
      name: 'UserCategory',
      lastPropertyId: const IdUid(4, 7125733078995242716),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6392309507137859323),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8269917080246794357),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4447172373678686381),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7125733078995242716),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 6944106862447846046),
            name: 'items',
            targetId: const IdUid(3, 7747437729085487469))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 7747437729085487469),
      name: 'UserItem',
      lastPropertyId: const IdUid(5, 3229825160880687799),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8516539469716402542),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4603267928841892304),
            name: 'type',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3018275137017811277),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8104732236004685307),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3229825160880687799),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 1143964970371906005),
            relationTarget: 'UserCategory')
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(2, 8338832137809488506),
            name: 'financialItem',
            targetId: const IdUid(4, 3895493335781458481))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3895493335781458481),
      name: 'UserFinancialItem',
      lastPropertyId: const IdUid(8, 1490969158113310321),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6964951509522846567),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2397990375380155432),
            name: 'amount',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8226837009802152727),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5099608274133152852),
            name: 'itemId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 3202762272567961640),
            relationTarget: 'UserItem'),
        ModelProperty(
            id: const IdUid(5, 7804851258891793720),
            name: 'date',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2216703801095526059),
            name: 'year',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 8766141389535259669),
            name: 'month',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1490969158113310321),
            name: 'day',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 7106698758550502341),
      name: 'UserWorkItem',
      lastPropertyId: const IdUid(5, 3024908084008019346),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3680039090176662234),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7839540658406756998),
            name: 'begin',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7747245824332721632),
            name: 'end',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3377597757378628690),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3024908084008019346),
            name: 'itemId',
            type: 11,
            flags: 520,
            indexId: const IdUid(4, 7194020369344260932),
            relationTarget: 'UserItem')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(5, 7106698758550502341),
      lastIndexId: const IdUid(4, 7194020369344260932),
      lastRelationId: const IdUid(2, 8338832137809488506),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [4228549374755142210],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        852269246544459326,
        1374442493824593795,
        290467816034440049,
        3094017730294721028
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserCategory: EntityDefinition<UserCategory>(
        model: _entities[0],
        toOneRelations: (UserCategory object) => [],
        toManyRelations: (UserCategory object) =>
            {RelInfo<UserCategory>.toMany(1, object.id): object.items},
        getId: (UserCategory object) => object.id,
        setId: (UserCategory object, int id) {
          object.id = id;
        },
        objectToFB: (UserCategory object, fb.Builder fbb) {
          final typeOffset =
              object.type == null ? null : fbb.writeString(object.type!);
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, typeOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final object = UserCategory(
              id: idParam,
              type: typeParam,
              title: titleParam,
              description: descriptionParam);
          InternalToManyAccess.setRelInfo<UserCategory>(
              object.items, store, RelInfo<UserCategory>.toMany(1, object.id));
          return object;
        }),
    UserItem: EntityDefinition<UserItem>(
        model: _entities[1],
        toOneRelations: (UserItem object) => [object.category],
        toManyRelations: (UserItem object) =>
            {RelInfo<UserItem>.toMany(2, object.id): object.financialItem},
        getId: (UserItem object) => object.id,
        setId: (UserItem object, int id) {
          object.id = id;
        },
        objectToFB: (UserItem object, fb.Builder fbb) {
          final typeOffset =
              object.type == null ? null : fbb.writeString(object.type!);
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, typeOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.category.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final object = UserItem(
              id: idParam,
              type: typeParam,
              title: titleParam,
              description: descriptionParam);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.category.attach(store);
          InternalToManyAccess.setRelInfo<UserItem>(object.financialItem, store,
              RelInfo<UserItem>.toMany(2, object.id));
          return object;
        }),
    UserFinancialItem: EntityDefinition<UserFinancialItem>(
        model: _entities[2],
        toOneRelations: (UserFinancialItem object) => [object.item],
        toManyRelations: (UserFinancialItem object) => {},
        getId: (UserFinancialItem object) => object.id,
        setId: (UserFinancialItem object, int id) {
          object.id = id;
        },
        objectToFB: (UserFinancialItem object, fb.Builder fbb) {
          final amountOffset =
              object.amount == null ? null : fbb.writeString(object.amount!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final yearOffset =
              object.year == null ? null : fbb.writeString(object.year!);
          final monthOffset =
              object.month == null ? null : fbb.writeString(object.month!);
          final dayOffset =
              object.day == null ? null : fbb.writeString(object.day!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, amountOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.item.targetId);
          fbb.addInt64(4, object.date?.millisecondsSinceEpoch);
          fbb.addOffset(5, yearOffset);
          fbb.addOffset(6, monthOffset);
          fbb.addOffset(7, dayOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final amountParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final dateParam = dateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateValue);
          final yearParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final monthParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final dayParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final object = UserFinancialItem(
              id: idParam,
              amount: amountParam,
              description: descriptionParam,
              date: dateParam,
              year: yearParam,
              month: monthParam,
              day: dayParam);
          object.item.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.item.attach(store);
          return object;
        }),
    UserWorkItem: EntityDefinition<UserWorkItem>(
        model: _entities[3],
        toOneRelations: (UserWorkItem object) => [object.item],
        toManyRelations: (UserWorkItem object) => {},
        getId: (UserWorkItem object) => object.id,
        setId: (UserWorkItem object, int id) {
          object.id = id;
        },
        objectToFB: (UserWorkItem object, fb.Builder fbb) {
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.begin?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.end?.millisecondsSinceEpoch);
          fbb.addOffset(3, descriptionOffset);
          fbb.addInt64(4, object.item.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final beginValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final endValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final beginParam = beginValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(beginValue);
          final endParam = endValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endValue);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final object = UserWorkItem(
              id: idParam,
              begin: beginParam,
              end: endParam,
              description: descriptionParam);
          object.item.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.item.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserCategory] entity fields to define ObjectBox queries.
class UserCategory_ {
  /// see [UserCategory.id]
  static final id =
      QueryIntegerProperty<UserCategory>(_entities[0].properties[0]);

  /// see [UserCategory.type]
  static final type =
      QueryStringProperty<UserCategory>(_entities[0].properties[1]);

  /// see [UserCategory.title]
  static final title =
      QueryStringProperty<UserCategory>(_entities[0].properties[2]);

  /// see [UserCategory.description]
  static final description =
      QueryStringProperty<UserCategory>(_entities[0].properties[3]);

  /// see [UserCategory.items]
  static final items =
      QueryRelationToMany<UserCategory, UserItem>(_entities[0].relations[0]);
}

/// [UserItem] entity fields to define ObjectBox queries.
class UserItem_ {
  /// see [UserItem.id]
  static final id = QueryIntegerProperty<UserItem>(_entities[1].properties[0]);

  /// see [UserItem.type]
  static final type = QueryStringProperty<UserItem>(_entities[1].properties[1]);

  /// see [UserItem.title]
  static final title =
      QueryStringProperty<UserItem>(_entities[1].properties[2]);

  /// see [UserItem.description]
  static final description =
      QueryStringProperty<UserItem>(_entities[1].properties[3]);

  /// see [UserItem.category]
  static final category =
      QueryRelationToOne<UserItem, UserCategory>(_entities[1].properties[4]);

  /// see [UserItem.financialItem]
  static final financialItem = QueryRelationToMany<UserItem, UserFinancialItem>(
      _entities[1].relations[0]);
}

/// [UserFinancialItem] entity fields to define ObjectBox queries.
class UserFinancialItem_ {
  /// see [UserFinancialItem.id]
  static final id =
      QueryIntegerProperty<UserFinancialItem>(_entities[2].properties[0]);

  /// see [UserFinancialItem.amount]
  static final amount =
      QueryStringProperty<UserFinancialItem>(_entities[2].properties[1]);

  /// see [UserFinancialItem.description]
  static final description =
      QueryStringProperty<UserFinancialItem>(_entities[2].properties[2]);

  /// see [UserFinancialItem.item]
  static final item = QueryRelationToOne<UserFinancialItem, UserItem>(
      _entities[2].properties[3]);

  /// see [UserFinancialItem.date]
  static final date =
      QueryIntegerProperty<UserFinancialItem>(_entities[2].properties[4]);

  /// see [UserFinancialItem.year]
  static final year =
      QueryStringProperty<UserFinancialItem>(_entities[2].properties[5]);

  /// see [UserFinancialItem.month]
  static final month =
      QueryStringProperty<UserFinancialItem>(_entities[2].properties[6]);

  /// see [UserFinancialItem.day]
  static final day =
      QueryStringProperty<UserFinancialItem>(_entities[2].properties[7]);
}

/// [UserWorkItem] entity fields to define ObjectBox queries.
class UserWorkItem_ {
  /// see [UserWorkItem.id]
  static final id =
      QueryIntegerProperty<UserWorkItem>(_entities[3].properties[0]);

  /// see [UserWorkItem.begin]
  static final begin =
      QueryIntegerProperty<UserWorkItem>(_entities[3].properties[1]);

  /// see [UserWorkItem.end]
  static final end =
      QueryIntegerProperty<UserWorkItem>(_entities[3].properties[2]);

  /// see [UserWorkItem.description]
  static final description =
      QueryStringProperty<UserWorkItem>(_entities[3].properties[3]);

  /// see [UserWorkItem.item]
  static final item =
      QueryRelationToOne<UserWorkItem, UserItem>(_entities[3].properties[4]);
}
